// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopJSewCSO0BrJoVD5IZU6HTMpFuTVGBc',
    appId: '1:530508085683:web:7fe60d6e253fb3fb7f73c6',
    messagingSenderId: '530508085683',
    projectId: 'bmproject2002',
    authDomain: 'bmproject2002.firebaseapp.com',
    storageBucket: 'bmproject2002.firebasestorage.app',
    measurementId: 'G-LRR49PFVKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjSwoQKglrvN4nQUrl-uRBemoyVkP4COM',
    appId: '1:530508085683:android:78b4a7f99a7bebd77f73c6',
    messagingSenderId: '530508085683',
    projectId: 'bmproject2002',
    storageBucket: 'bmproject2002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEPeL4WXl-1q3kMwbDWMpgpEu0mkrynQ',
    appId: '1:530508085683:ios:7bd3fbafe5c365467f73c6',
    messagingSenderId: '530508085683',
    projectId: 'bmproject2002',
    storageBucket: 'bmproject2002.firebasestorage.app',
    iosBundleId: 'com.example.bmproject',
  );
}
